dirs:
    exp: fisher
    type: scp_classify
    train:
        scp: /mnt/lustre/xushuang2/easton/data/fisher/train/feats.scp.train
        label: /mnt/lustre/xushuang2/easton/data/fisher/train/label_01_02_03.train
        tfdata: /mnt/lustre/xushuang2/easton/data/fisher/tfdata/train_div3
    dev:
        scp: /mnt/lustre/xushuang2/easton/data/fisher/test/feats.scp.test
        label: /mnt/lustre/xushuang2/easton/data/fisher/test/label_01_02_03.test
        tfdata: /mnt/lustre/xushuang2/easton/data/fisher/tfdata/test_div3
    test:
        scp: /mnt/lustre/xushuang2/easton/data/fisher/test/feats.scp.test
        label: /mnt/lustre/xushuang2/easton/data/fisher/test/label_01_02_03.test
    vocab: /mnt/lustre/xushuang2/easton/data/hkust/char_3673+1.vocab
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/EODM/exps/fisher/fisher/checkpoint

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    structure: classifier
    encoder:
        structure: classifier
        num_hidden: 1600
        num_filters: 64
        dropout: 0.9
    decoder:
        structure: classifier
opti:
    type: adam
    lr: 0.0004

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 999

optimizer: adam
warmup_steps: 6000
peak: 0.0002
decay_steps: 8000

gpus: '4'
batch_size: 60
beam_size: 1
num_supervised:
num_batch_tokens: 5000
bucket_boundaries: 1000,1200,1300,1400,1500,1600
seed: 8

lambda_l2: 0.0
grad_clip_value: 0.0
slot_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
