dirs:
    exp: aishell
    train:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-5k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-5k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-5k_xy
    untrain:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_xy
    dev:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.dev-14k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/dev-14k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/dev-14k_xy
    test:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.test-7k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/test-7k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/test-7k_xy
    text:
        data: /mnt/lustre/xushuang2/easton/data/aishell/char/text.char
    type: scp
    vocab: /mnt/lustre/xushuang2/easton/data/aishell/char/vocab_2818.text
    # checkpoint_G: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_ctc2/no_norm_5k/checkpoint/model-799
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/libri/libri_transformer/test2/checkpoint

# data:
#     featType: mfcc
#     left_context: 0
#     right_context: 0
#     downsample: 1
#     add_delta: False
#     unit: word

model:
    type: ctcModel
    num_blocks: 10
    hidden_size: 512
    num_fc: 3
    encoder:
        type: conv2
    decoder:
        type: FC

model_D:
    type: clm
    num_blocks: 10
    hidden_size: 512
    num_fc: 2
    max_feat_len: 1000

# lr_type: constant_learning_rate
optimizer: adam
# lr: 0.0001
lr_G: 0.0005
lr_D: 0.0005
supervise_G_rate: 1.0
warmup_steps: 2000
peak: 0.0002
decay_steps: 3000

decode_step: 100
save_step: 600
num_epochs: 999

# gpus: '0,1,2,3'
# gpus: '0,1,2,3'
# gpus: '4,5,6,7'
gpus: '4,5,6,7'
batch_size: 160
beam_size: 1
text_batch_size: 300
max_label_len: 20
num_batch_tokens: 30000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
