dirs:
    exp: aishell
    train:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-10k.scp
        phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-10k_rmsil.phone67
        char: /mnt/lustre/xushuang2/easton/data/aishell/char/train-10k.char
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-10k_phone_char
        #scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        #phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k_rmsil.phone67
        #char: /mnt/lustre/xushuang2/easton/data/aishell/char/train-120k.char
        #tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_phone_char
    untrain:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k_rmsil.phone67
        char: /mnt/lustre/xushuang2/easton/data/aishell/char/train-120k.char
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_phone_char
    dev:
        # scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-1k.scp
        # phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-1k_rmsil.phone67
        # char: /mnt/lustre/xushuang2/easton/data/aishell/char/train-1k.char
        # tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-1k_phone_char
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.dev-14k.scp
        phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/dev-14k_rmsil.phone67
        char: /mnt/lustre/xushuang2/easton/data/aishell/char/dev-14k.char
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/dev-14k_phone_char
    test:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.test-7k.scp
        phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/test-7k_rmsil.phone67
        char: /mnt/lustre/xushuang2/easton/data/aishell/char/test-7k.char
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/test-7k_phone_char
    text:
        data: /mnt/lustre/xushuang2/easton/data/aishell/phone/text-120k.phone67
    type: scp_multi
    vocab_phone: /mnt/lustre/xushuang2/easton/data/aishell/phone/phones_67+1.vocab
    vocab: /mnt/lustre/xushuang2/easton/data/aishell/char/char_2818.vocab
    # checkpoint_G: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_Ectc_Docd_2/120k_ctc/checkpoint/model_G-17799
    checkpoint_G: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_phone2char/2_conv_splice_0_0_DEhalf_1-2/checkpoint/model_G-12999
    # checkpoint_G_en: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_ctc2/10k/checkpoint/model-4199
data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    type: Ectc_Docd_Multi
    dropout: 0.05
    confidence_penalty: 0.2
    encoder:
        type: conv2
        num_filters: 256
        num_blocks: 2
    decoder:
        type: conv_decoder
        num_blocks: 2
        num_filters: 64
        hidden_size: 256
        num_fc: 2
        label_smoothing: 0.95
        left_splice: 0
        right_splice: 0
        half: True

model_D:
    type: clm
    hidden_size: 256
    num_blocks: 5
    num_fc: 2

# lr_type: constant_learning_rate
optimizer: adam
rate: 2.0
lr_G: 0.00001
lr_D: 0.00001
lr: 0.00001
warmup_steps: 2000
peak: 0.001
decay_steps: 3000
# warmup_steps: 1000
# peak: 0.0002
# decay_steps: 1200

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 999

# gpus: '0,1,2,3'
# gpus: '1,2,3'
# gpus: '4,5,6,7'
gpus: '4,5'
batch_size: 150
beam_size: 1
text_batch_size: 200
max_feat_len: 1230
max_label_len: 20
num_batch_tokens: 40000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
