dirs:
    exp: aishell
    train:
        # scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-1k.scp
        # trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-1k.phone67
        # tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-1k_xy
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_xy
    untrain:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_xy
    dev:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.dev-14k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/dev-14k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/dev-14k_xy
    test:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.test-7k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/test-7k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/test-7k_xy
    text:
        data: /mnt/lustre/xushuang2/easton/data/aishell/phone/text-120k.phone67
    type: scp
    vocab: /mnt/lustre/xushuang2/easton/data/aishell/phone/phones_67+1.vocab
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_Ectc_Docd/checkpoint/model-999
    checkpoint_G_en: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_Ectc_Docd/checkpoint/model_G_en-40999

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    type: Ectc_Docd
    dropout: 0.05
    encoder:
        type: conv2
        # type: conv_lstm
        num_filters: 64
        num_blocks: 2
        hidden_size: 256
        num_fc: 3
    decoder:
        type: conv_decoder
        # type: FC
        num_filters: 128
        num_blocks: 1
        hidden_size: 256
        num_fc: 3
        label_smoothing: 0.95

model_D:
    type: clm
    hidden_size: 256
    num_blocks: 5
    num_fc: 2

# lr_type: constant_learning_rate
optimizer: adam
rate: 0.2
lr_G: 0.0001
lr_D: 0.0001
# lr: 0.00001
warmup_steps: 2000
peak: 0.001
decay_steps: 3000
# warmup_steps: 300
# peak: 0.0005
# decay_steps: 600

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 999

# gpus: '0,1,2,3'
gpus: '1,2,3'
# gpus: '4,5,6,7'
# gpus: '4,5'
batch_size: 200
beam_size: 1
text_batch_size: 200
max_feat_len: 1230
max_label_len: 60
num_batch_tokens: 60000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
