dirs:
    exp: aishell
    train:
        scp: /home/easton/data/AISHELL/feats/feats.train-120k.scp
        trans: /home/easton/data/AISHELL/char/train-120k.char
        tfdata: /home/easton/data/AISHELL/char/tfdata/train-char-120k
    dev:
        scp: /home/easton/data/AISHELL/feats/feats.dev-14k.scp
        trans: /home/easton/data/AISHELL/char/dev-14k.char
        tfdata: /home/easton/data/AISHELL/char/tfdata/dev-char-14k_1
    test:
        scp: /home/easton/data/AISHELL/feats/feats.test-7k.scp
        trans: /home/easton/data/AISHELL/char/test-7k.char
        tfdata: /home/easton/data/AISHELL/char/tfdata/test-char-7k
    type: scp
    vocab: /home/easton/data/AISHELL/char/char.vocab
    # checkpoint: /home/easton/projects/asr-tf1/exps/aishell/aishell_transformer_char/120k/checkpoint/model-50399

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word
    add_eos: False

model:
    type: ctcModel
    confidence_penalty: 0.2
    # encoder:
    #     type: conv2
    #     # type: conv_lstm
    #     num_filters: 256
    #     num_blocks: 2
    # decoder:
    #     type: FC
    #     hidden_size: 256
    #     num_fc: 2
    #     label_smoothing: 0.95
    encoder:
        type: conv_lstm
        num_filters: 64
        hidden_size: 512
    decoder:
        type: FC
        hidden_size: 256
        num_fc: 0
        label_smoothing: 0.95

optimizer: adam
warmup_steps: 5000
peak: 0.0005
decay_steps: 8000

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 99999

# gpus: '0,1,2,3'
# gpus: '4,5'
# gpus: '4,5,6,7'
gpus: '6,7'
batch_size: 200
beam_size: 1
text_batch_size: 200
max_feat_len: 1230
max_label_len: 60
num_batch_tokens: 40000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
