dirs:
    exp: aishell
    train:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-10k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-10k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-10k_xy
    untrain:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.train-120k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/train-120k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/train-120k_xy
    dev:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.dev-14k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/dev-14k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/dev-14k_xy
    test:
        scp: /mnt/lustre/xushuang2/easton/data/aishell/feats/feats.test-7k.scp
        trans: /mnt/lustre/xushuang2/easton/data/aishell/phone/test-7k.phone67
        tfdata: /mnt/lustre/xushuang2/easton/data/aishell/phone/tfdata/test-7k_xy
    text:
        data: /mnt/lustre/xushuang2/easton/data/aishell/phone/text-120k.phone67
    type: scp
    vocab: /mnt/lustre/xushuang2/easton/data/aishell/phone/phones_67+1.vocab
    checkpoint_G: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_ctc/merge_false_train-10k/checkpoint
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/libri/libri_transformer/test2/checkpoint

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    type: ctcModel
    encoder:
        type: conv
        num_filters: 128
    decoder:
        type: FC

model_D:
    type: clm
    num_hidden: 256
    num_blocks: 5
    max_feat_len: 1000

# lr_type: constant_learning_rate
optimizer: adam
# lr: 0.0001
lr_G: 0.00001
lr_D: 0.00001
supervise_G_rate: 20.0
warmup_steps: 2000
peak: 0.0002
decay_steps: 3000
# warmup_steps: 600
# peak: 0.0002
# decay_steps: 1000

dev_step: 20000
decode_step: 60000
save_step: 600
num_epochs: 999

gpus: '0,1,2,3'
# gpus: '0,1,2,3'
# gpus: '4,5,6,7'
# gpus: '6,7'
batch_size: 120
beam_size: 1
text_batch_size: 120
max_label_len: 40
num_batch_tokens: 30000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
