dirs:
    exp: timit_phone
    train:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/train/text
        wav_scp: /home/user/easton/data/TIMIT/kaldi_gentrain_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_feats_13_0_1_3
    train_supervise:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/train/text_200
        wav_scp: /data/sxu/easton/data/TIMIT/train200_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train200_feats_13_0_1_3
    dev:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
        wav_scp: /data/sxu/easton/data/TIMIT/test_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/test_feats_13_0_1_3
    text:
        # data: /mnt/lustre/xushuang2/easton/data/aishell/phone/text-120k.phone67
        data: /home/user/easton/data/AISHELL/char/train-120k.char
        supervise: /home/user/easton/data/AISHELL/char/train-1k.char
        # supervise: /home/user/easton/data/AISHELL/char/train-120k.char
        dev: /home/user/easton/data/AISHELL/char/dev-14k.char
    type: test
    vocab_pinyin: /home/user/easton/data/AISHELL/char/pinyin_1383.txt
    vocab: /home/user/easton/data/AISHELL/char/char_2817.vocab
    # checkpoint_G: /home/user/easton/projects/asr-tf1/exps/gen_text/aishell_phone/2k_noise2.5/checkpoint/model-10999
    # checkpoint_G: /home/user/easton/projects/asr-tf1/exps/gen_text/aishell_phone/100_fc/checkpoint/model-1099
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/libri/libri_transformer/test2/checkpoint

# data:
#     featType: mfcc
#     left_context: 0
#     right_context: 0
#     downsample: 1
#     add_delta: False
#     unit: word

model:
    type: ctcModel
    dim_input: 10
    num_filters: 128
    num_blocks: 1
    hidden_size: 256
    num_fc: 3
    dropout: 0.05
    encoder:
        type: conv2
    decoder:
        type: FC

model_D:
    type: clm
    num_blocks: 10
    hidden_size: 256
    num_fc: 2
    max_feat_len: 1000

noise: 5.0
uprate: 1.0
# lr_type: constant_learning_rate
optimizer: adam
# lr: 0.0001
rate: 0.2
lr_G: 0.001
lr_D: 0.001
supervise_G_rate: 1.0
warmup_steps: 5000
peak: 0.001
decay_steps: 8000

decode_step: 100
dev_step: 100
save_step: 100
num_epochs: 999

# gpus: '0,1,2,3'
# gpus: '0,1,2,3'
# gpus: '4,5,6,7'
gpus: '0'
batch_size: 160
beam_size: 1
text_batch_size: 200
max_label_len: 20
num_supervised: 1000
num_batch_tokens: 20000
bucket_boundaries: 308,343,373,403,432,465,500,537,578,629,706,905,1230

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
