dirs:
    exp: callhome
    train:
        scp: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.scp
        trans: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/train_char
    dev:
        scp: /home/easton/data/CALLHOME/Mandarin/dev_dim80/dev.scp
        trans: /home/easton/data/CALLHOME/Mandarin/dev_dim80/dev.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/dev_char
    test:
        scp: /home/easton/data/CALLHOME/Mandarin/test_dim80/test.scp
        trans: /home/easton/data/CALLHOME/Mandarin/test_dim80/test.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/test_char
    type: scp
    vocab: /home/easton/data/CALLHOME/Mandarin/train_dim80/char_2214+1.vocab
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_ctc2/1k/checkpoint/model-599
    # checkpoint: /mnt/lustre/xushuang2/easton/projects/asr-tf1/exps/aishell/aishell_ctc2/Ectc_Docd/checkpoint/model-10799

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word

model:
    type: ctcModel
    confidence_penalty: 0.2
    encoder:
        type: conv2
        num_filters: 256
        num_blocks: 2
    decoder:
        type: FC
        hidden_size: 256
        num_fc: 2
        label_smoothing: 0.95

optimizer: adam
warmup_steps: 1000
peak: 0.0005
decay_steps: 2000

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 99999

gpus: '0,1,2,3'
# gpus: '4,5'
# gpus: '4,5,6,7'
# gpus: '6,7'
batch_size: 200
beam_size: 1
text_batch_size: 200
max_feat_len: 1230
max_label_len: 60
num_batch_tokens: 200000
bucket_boundaries: 89,162,231,306,398,530,804,1958,4036

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
