dirs:
    exp: callhome
    train:
        scp: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.scp
        phone: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.phone
        char: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/train_phone_char
    untrain:
        scp: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.scp
        phone: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.phone
        char: /home/easton/data/CALLHOME/Mandarin/train_dim80/train.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/train_phone_char
        # scp: /home/easton/data/HKUST/HKUST_80/train/feats.scp
        # phone: /home/easton/data/HKUST/HKUST_80/train/train_clean.phone
        # char: /home/easton/data/HKUST/HKUST_80/train/train_clean.char
        # tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/hkust_phone_char
    dev:
        scp: /home/easton/data/CALLHOME/Mandarin/dev_dim80/dev.scp
        phone: /home/easton/data/CALLHOME/Mandarin/dev_dim80/dev.phone
        char: /home/easton/data/CALLHOME/Mandarin/dev_dim80/dev.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/dev_phone_char
    test:
        scp: /home/easton/data/CALLHOME/Mandarin/test_dim80/test.scp
        phone: /home/easton/data/CALLHOME/Mandarin/test_dim80/test.phone
        char: /home/easton/data/CALLHOME/Mandarin/test_dim80/test.char
        tfdata: /home/easton/data/CALLHOME/Mandarin/tfdata/test_phone_char
    text:
        data: /home/easton/data/HKUST/HKUST_80/train/text.char
    type: scp_multi
    vocab_phone: /home/easton/data/CALLHOME/Mandarin/phones.vocab
    vocab: /home/easton/data/CALLHOME/Mandarin/char.vocab
    # checkpoint_G: /home/easton/projects/asr-tf1/exps/callhome/callhome_Ectc-Docd-Multi/supervise_share_encoder/checkpoint/model_G-4799

data:
    featType: mfcc
    left_context: 0
    right_context: 0
    downsample: 1
    add_delta: False
    unit: word
    add_eos: False

model:
    type: Ectc_Docd_Multi
    dropout: 0.05
    confidence_penalty: 0.2
    encoder:
        # type: conv2
        # num_filters: 256
        # num_blocks: 2
        type: conv_lstm
        num_filters: 64
        hidden_size: 256
    decoder:
        type: conv_decoder
        num_blocks: 2
        num_filters: 64
        hidden_size: 256
        num_fc: 2
        label_smoothing: 0.95
        left_splice: 0
        right_splice: 0
        share_encoder: True
        half: True
model_D:
    type: clm
    hidden_size: 256
    num_blocks: 5
    num_fc: 2

# lr_type: constant_learning_rate
optimizer: adam
rate: 0.1
lr_G: 0.0001
lr_D: 0.0001
lr: 0.00001
warmup_steps: 2000
peak: 0.001
decay_steps: 3000
# warmup_steps: 1000
# peak: 0.0002
# decay_steps: 1200

dev_step: 200
decode_step: 200
save_step: 200
num_epochs: 999
sample_uttid: ma_0003-A-009398-009677
# gpus: '0,1,2,3'
# gpus: '1,2,3'
# gpus: '4,5,6,7'
gpus: '4,5'
batch_size: 150
beam_size: 1
text_batch_size: 200
max_feat_len: 1230
max_label_len: 20
num_batch_tokens: 40000
# bucket_boundaries: 89,162,232,308,401,536,819,2085,4036
bucket_boundaries: 69,122,170,216,264,315,375,447,548,718,1119,3681,4036

lambda_lm: 0.0
lambda_l2: 0.0
grad_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
